### ISSUE TITLE
不同发行版分别采用了 yq 的两个不同上游

### ISSUE THREAD

**Issue by weilinfox** [weilinfox/ruyi-litester#5]
有两个 yq 分别来自不同的上游 [kislyuk/yq](https://github.com/kislyuk/yq) 和 [mikefarah/yq](https://github.com/mikefarah/yq)

而当前 ruyi-litester 基于了 kislyuk/yq，这在 Ubuntu、 Fedora 上会导致问题。

**Comment by Cyl18** [comment]
全用 `pip` 装应该就能解决吧

**Comment by weilinfox** [comment]
Fix by commit https://github.com/weilinfox/ruyi-litester/commit/46de01258bddc2ba9fd9f1c4ddef8e164d3e13d2
